server:
  port: 8081

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://localhost:3306/project_db_2?createDatabaseIfNotExist=true
    username: root
    password: jujuRO55
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true