server:
  port: 8083

spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:mysql://resourcedb:3306/resource_db_2?createDatabaseIfNotExist=true
    username: springstudent
    password: springstudent
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true